In [ ]:
X = 12
if (X > 10 & X < 15):
    print('YES')
else:
    print('No')

In [ ]:
a=40
b=30
c=20

if( a > b and a > c):
    print("a")
elif(b > a and b > c):
    print("b")
else:
     print("c")

In [ ]:
if (10 < 0) and (0 < -10):
    print("A")
elif (10 > 0) or False:
    print("B")
else:
    print("C")

In [ ]:
if True or True:
    if False and True or False:
        print('A')
    elif False and False or True and True:
        print('B')
    else:
        print('C')
else:
    print('D')

In [ ]:
d = {0: 'fish', 1: 'bird', 2: 'Mammal'}

for i in d:
    print(i)

In [ ]:
n = 4

for i in range(1, n+1):
    print(i)

In [ ]:
def func(x, y = 1):
    z = x * y + x + y
    return z

func(2, func(3))

In [ ]:
func(3)

In [ ]:
L1 = [2, 7, 8, 10, 3]

def func(y):
    return y**2 - 2 * y - 2

ans_list = [func(x) for x in L1 ]
ans_list

In [ ]:
min = (lambda x, y: x if x < y else y)
min(101*99, 102*98)

In [ ]:
x = ['Santa Cruz', 'Santa fe','Mumbai', 'Delhi']

def res(string):
    if string[0].upper() == 'S':
        return string
    
res = map(res, x)
out = list(filter(lambda x: x is not None, res))
print(len(out))

In [ ]:
input_list = [ ['Ankur','Avik','Kiran','Nitin'],['Narang','Sarkar','R','Sareen']]

first_name = input_list[0]
last_name = input_list[1]

output = map(lambda x, y: x + ' ' + y, first_name, last_name)
list(output)

In [ ]:
input_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

list_answer = list(filter(lambda x: x%5 ==0, input_list))
list_answer 

In [ ]:
input_list = ['soap','sharp','shy','silent','ship','summer','sheep']

sp = list(filter(lambda x: x[0].lower() == 's' and x[-1].lower() == 'p', input_list))
sp

In [ ]:
from functools import reduce

input_list = ['All','you','have','to','fear','is','fear','itself']

output = reduce(lambda x, y: x + ' ' + y, input_list)

output

In [ ]:
input_list = [65,76,87,23,12,90,99]

answer = reduce(lambda x, y: x if x > y else y, input_list)

answer

In [ ]:
input_string = "I love Python"
k = [(i.upper(), len(i)) for i in input_string.split(' ')]
print(k)

In [ ]:
var = [i**2 for i in range(5)]
print(var)

In [ ]:
def function(n):
  n=n+1
 
n=2
print(function(2))

In [ ]:
def samplefunc(msg,i=3):
  print(msg*i)
 
samplefunc('python',4)
samplefunc('program')

In [ ]:
f=lambda x:bool(x%2)
print(f(100)* f(101))

In [ ]:
input_string = "I love Python"
k = [(i.upper(), len(i)) for i in input_string.split(' ')]
print(k)

In [ ]:
l=(1, -2, -3, 4, 5)
def f1(x):
    return x//2
m1=map(f1, l)
print(list(m1))

In [ ]:
from functools import reduce
numbers = [-1, 2, -5, 3, 8,-2, 1,-4,-2]
sum = reduce(lambda x, y: x + y, numbers)
print(sum)

In [ ]:
import functools

lis=[1, 2, 3, 4, 5]

m=functools.reduce(lambda x, y:x if x<y else y, lis)

print(m)

In [ ]:
lis=[1, 2, 3, 4, 5]

c=lis[0]

for i in range(len(lis)-1):

    if lis[i]<c:

       c=lis[i]

print(c)

In [ ]:
def sf(a):
    return a%4==0 and a%8!=0
m=filter(sf, range(10, 31))
print(list(m))

In [ ]:
input_list = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61]

output = list(map(lambda x: x*3, input_list))
print(output)

In [ ]:
input_list = ['Ronaldo', 'Cristiano', 'Rakesh', 'Ronak']

output = list(map(lambda x: x[::-1].upper(), input_list))
print(output)

In [ ]:

# Function to find common names in 3 lists
def find_common_names(list1, list2, list3):
    # Convert lists to sets
    set1 = set(list1)
    set2 = set(list2)
    set3 = set(list3)
    
    # Find intersection of all 3 sets
    common_names = set1.intersection(set2, set3)
    
    return list(common_names)

# Example usage
names1 = ["John", "Emma", "Michael", "Sarah"]
names2 = ["Emma", "James", "Sarah", "William"] 
names3 = ["Sarah", "Emma", "Thomas", "Elizabeth"]

common = find_common_names(names1, names2, names3)
print("Common names:", common)

In [5]:
input_list = [{ "name" : "Mohan", "rank" : 2}, { "name" : "Mandeep", "rank" : 2 }, { "name" : "Merut" , "rank" : 2 }]

output = sorted(input_list, key=lambda x: (x["rank"], x["name"]))
output

[{'name': 'Mandeep', 'rank': 2},
 {'name': 'Merut', 'rank': 2},
 {'name': 'Mohan', 'rank': 2}]

In [9]:
input_list = [{4: 'Viking', 9: 'Happy', 10: 'Tony', 2: 'Rogers'}, {12: 'Vikram', 19: 'Vipan'}, {3: 'Kohli'}, {1: 'Ronaldo', 29: 'Harish', 7: 'Ganesh'}]

output = sorted(input_list, key=lambda x: len(x), reverse=True)

print(output)

[{4: 'Viking', 9: 'Happy', 10: 'Tony', 2: 'Rogers'}, {1: 'Ronaldo', 29: 'Harish', 7: 'Ganesh'}, {12: 'Vikram', 19: 'Vipan'}, {3: 'Kohli'}]


In [13]:
import numpy as np

np.array((1, 1.2))

array([1. , 1.2])

In [20]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[ : : -2])

[2, 5, 7, 4, 3, 1]


In [27]:
input_list=[ 1, 5, 9, 12, 15, 7, 12, 9 ]
m=6
n=12

import numpy as np
array_1 = np.array(input_list)
final_array = array_1[(array_1 > m) & (array_1 < n)]

print(final_array)

[9 7 9]


In [31]:
array_1 = np.array([[1, 3, 5, 4],[2,3,5,6]])
array_1

array([[1, 3, 5, 4],
       [2, 3, 5, 6]])

In [34]:
array_1[ : , :3] 

array([[1, 3, 5],
       [2, 3, 5]])

In [46]:
array_2d = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
array_2d
# appropriate indexing
col_first = array_2d[0: , 0]
row_first = array_2d[0]
col_last = array_2d[0:, -1]
row_last = array_2d[-1]

print(col_first)
print(row_first)
print(col_last)
print(row_last)

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [53]:
n = 2

# Create an 'n*n' array of all ones
array_2d = np.ones([n, n], dtype=int)

# Fill the array with zeroes from second index (i.e. index 1) to second last index.
# Do this for both row indices and column indices
array_2d[1:-1, 1:-1] = 0

# Print the array created
print(array_2d)

[[1 1]
 [1 1]]


In [55]:
import re
#1. Extract all the words
text = "Welcome to"
print(re.findall(r'\w', text))

['W', 'e', 'l', 'c', 'o', 'm', 'e', 't', 'o']


In [57]:
# 1. Find all words in the sentence
# Extract all words (alphanumeric + underscore) from this string:
text = "Welcome_to Regex101! Learn & practice now."
print(re.findall(r'\w+', text))

['Welcome_to', 'Regex101', 'Learn', 'practice', 'now']


In [58]:
# 2. Check if a string starts with 'Hi'
text = "Hi there!"
print(re.findall(r'^Hi', text))

['Hi']


In [68]:
# 3. Find all digits in the string
text = "Room number 42, Floor 5"
print(re.findall(r'\d+', text))

['42', '5']


In [66]:
# 4. Match if string ends with a question mark
text = 'Are you coming?'
print(re.search(r'\?$', text).group())

?


In [74]:
input_list = [[[7, 13, 14], [18, 10, 17], [11, 12, 19]], [16, 6, 1], [[5, 8, 4, 3]]]
list_1 = input_list[0]
list_2 = input_list[1]
list_3 = input_list[2]


# Write your code here
final_array = np.vstack((list_1, list_2))
final_array = np.hstack((final_array, np.transpose(list_3)))
print(final_array)


[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [3]:
# sample text to perform preprocessing
text = "It's interesting to see how Natural Language Processing (NLP) has evolved over the years. NLP is a subfield of artificial intelligence (AI) that focuses on the interaction between computers and humans. NLP techniques are used to analyze text, allowing machines to understand how humans speak. This human-computer interaction enables real-world applications like automatic text summarization, sentiment analysis, topic extraction, named entity recognition, parts-of-speech tagging, relationship extraction, stemming, and more. NLP is commonly used for text mining, machine translation, and automated question answering."
text

"It's interesting to see how Natural Language Processing (NLP) has evolved over the years. NLP is a subfield of artificial intelligence (AI) that focuses on the interaction between computers and humans. NLP techniques are used to analyze text, allowing machines to understand how humans speak. This human-computer interaction enables real-world applications like automatic text summarization, sentiment analysis, topic extraction, named entity recognition, parts-of-speech tagging, relationship extraction, stemming, and more. NLP is commonly used for text mining, machine translation, and automated question answering."

In [82]:
cleaned = re.sub(r'\W',' ', text)
cleaned = re.sub(r'\d', '', cleaned).lower()
cleaned

'it s interesting to see how natural language processing  nlp  has evolved over the years  nlp is a subfield of artificial intelligence  ai  that focuses on the interaction between computers and humans  nlp techniques are used to analyze text  allowing machines to understand how humans speak  this human computer interaction enables real world applications like automatic text summarization  sentiment analysis  topic extraction  named entity recognition  parts of speech tagging  relationship extraction  stemming  and more  nlp is commonly used for text mining  machine translation  and automated question answering '

In [1]:
import numpy as np

array_1 = np.array(range(1, 11*12+1))
array_1 = array_1.reshape(11, 12)
array_1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]])

In [2]:
np.unravel_index(99, (11,12))

(8, 3)

In [5]:
array_1 = np.array([[1, 5],
 [3, 7],
 [4, 9]])

np.reshape(array_1, -1)

array([1, 5, 3, 7, 4, 9])

In [7]:
array_1 = np.array([[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]])

In [9]:
print(array_1[array_1%2 != 0]) 

[ 1  3  5  7  9 11 13 15 17 19]


In [10]:
print(array_1[array_1%2 == 0].reshape(5, 2)) 

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [13]:
array_1 = np.array([[1, 5],
 [3, 7],
 [4, 9]])

np.reshape(array_1, (1, -1))

array([[1, 5, 3, 7, 4, 9]])